[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r r.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn config.wsgi:application -c gunicorn.conf.py"
