services:
  - type: web
    name: ff-tournament-pro
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application -c gunicorn.conf.py"
